services:
  jewishpulse:
    build: .
    restart: always
    init: true
    tty: true
    volumes:
      - ./:/app
    command: php /app/main.php

  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app
