name: GitHub Release to Telegram

on:
  release:
    types: [published]

jobs:
  send-to-telegram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install

      - name: Send release info to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_REPO_OWNER: ${{ secrets.REPO_OWNER }}
          GITHUB_REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          php webhook.php
